version: '3'
services:
  app:
    container_name: app
    hostname: app
    privileged: false
    build: ./app/
    ports:
      - '8081:8081'
    environment:
      - TWILIO_SID=changeme
      - TWILIO_AUTH_TOKEN=changeme
      - TWILIO_PHONE_NUMBER=changeme
      - BASE_URL=http://changeme:changeme@domain-changeme.tld:8081/
